<?php

declare(strict_types=1);

namespace uhc\scenarios\modules\backpacks;

use muqsit\invmenu\inventory\InvMenuInventory;
use pocketmine\Player;

/**
 * Class BackpackInventory
 * @package uhc\scenarios\modules\backpacks
 */
class BackpackInventory extends InvMenuInventory
{

    /**
     * @param Player $who
     */
    public function onOpen(Player $who): void
    {
        parent::onOpen($who); // TODO: Change the autogenerated stub
    }

    /**
     * @param Player $who
     */
    public function onClose(Player $who): void
    {
        parent::onClose($who); // TODO: Change the autogenerated stub
    }
}